AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  QueueName:
    Type: String
    Description: The name of the SQS queue

Resources:
  SQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Ref QueueName

Outputs:
  QueueURL:
    Value: !GetAtt SQSQueue.QueueUrl
    Export:
      Name: !Sub "${AWS::StackName}-QueueURL"
